In [73]:
import cvxpy as cp
import numpy as np
import pandas as pd

## 1.2

### 1.1

In [70]:
x = cp.Variable((2), nonneg=True, integer=True)
objective = cp.Maximize(x[0] * 4000 + x[1] * 3000)

constraints = [x[0] * 2 + x[1] <= 10, x[0] + x[1] <= 8, x[1] <= 7]

problem = cp.Problem(objective, constraints)
problem.solve()

print(f"Optimal value: {problem.value}")
print(f"x = {x.value}")

Optimal value: 26000.0
x = [2. 6.]


### 1.3

In [5]:
x1, x2, x3 = (
    cp.Variable(nonneg=True),
    cp.Variable(nonneg=True),
    cp.Variable(nonneg=True),
)

objective = cp.Maximize(x1 * 2 + x2 * 3 - x3 * 5)

constraints = [x1 + x2 + x3 == 7, x1 * 2 - x2 * 5 + x3 >= 10, x1 + x2 * 3 + x3 <= 12]

problem = cp.Problem(objective, constraints)
problem.solve()

print(f"Optimal value: {problem.value:.3f}")
print(f"x1 = {x1.value:.3f}\nx2 = {x2.value:.3f}\nx3 = {x3.value:.3f}")

Optimal value: 14.571
x1 = 6.429
x2 = 0.571
x3 = 0.000


### 1.4

In [72]:
x = cp.Variable((4, 4), nonneg=True, integer=True)

objective = cp.Minimize(
    2800 * sum(x[0:4, 0])
    + 4500 * sum(x[0:3, 1])
    + 6000 * sum(x[0:2, 2])
    + 7300 * x[0, 3]
)

constraints = [
    sum(x[0, :]) >= 15,
    sum(x[0, 1:]) + sum(x[1, 0:4]) >= 10,
    sum(x[0, 2:]) + sum(x[1, 1:3]) + sum(x[2, 0:2]) >= 20,
    x[0, 3] + x[1, 2] + x[2, 1] + x[3, 0] >= 12,
    x[1, 3] == 0,
    x[2, 2] == 0,
    x[2, 3] == 0,
    x[3, 1] == 0,
    x[3, 2] == 0,
    x[3, 3] == 0,
]

problem = cp.Problem(objective, constraints)
problem.solve()

print(f"Optimal value: {problem.value:.0f}")
print(f"x = {np.abs(x.value)}")

Optimal value: 118400
x = [[ 3.  0.  0. 12.]
 [ 0.  0.  0.  0.]
 [ 8.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


### 1.5

In [84]:
data_header = ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "产量"]
data1 = pd.read_csv("data/data1_5.csv", names=data_header)
data1

,B1,B2,B3,B4,B5,B6,B7,B8,产量
0,6,2,6,7,4,2,5,9,60.0
1,4,9,5,3,8,5,8,2,55.0
2,5,2,1,9,7,4,3,3,51.0
3,7,6,7,3,9,2,7,1,43.0
4,2,3,9,5,7,2,6,5,41.0
5,5,5,2,2,8,1,4,3,52.0
6,35,37,22,32,41,32,43,38,NaN
